meta_product_name: "Suricat"
meta_title: "Suricat - Manage your job opportunities in one place"
meta_description: "Save, gather and keep track of all your job opportunities in one place to spot the most fitted job"
